apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadxhnh6211-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadxhnh6211-tenant-component
    app.kubernetes.io/part-of: loadxhnh6211-tenant-app
  name: loadxhnh6211-tenant-component
  namespace: loadxhnh6211-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadxhnh6211-tenant-component
    weight: null
status: {}
